### ISSUE TITLE
Download speed

### ISSUE THREAD

**Issue by DieVei** [KevCui/animepahe-dl#12] opened 2021-01-09 08:28 UTC
for some reason the download speed is very low compared to normal downloads from the site. it took around 8 mins to download a 240mb episode. Can you please fix this? I have a 100mbps connection and usually get around 5-8mbps when downloading from the website.

**Comment by KevCui** [comment] 2021-01-09 08:59
Hi @DieVei, there is no specific implementation in the script that will limit or affect download speed. All I can think for now is that it might be the restriction from server side. I'll take a look.

**Comment by KevCui** [comment] 2021-01-10 13:02
Another possible cause of your slow downloading speed is `ffmpeg`. The script is using `ffmpeg` to download and concatenate video. Thus, the cpu processing power might also impact `ffmpge`'s speed. I tried different `ffmpeg` options to see if I can gain the processing speed increase. But unfortunately, so far I am not able to make it faster than current state. :disappointed:

**Comment by Akianonymus** [comment] 2021-01-11 09:50
@KevCui It's definitely due to ffmpeg.

To solve this, just download the seperate ts files with curl, and merge it all with ffmpeg.

The URLs will be in m3u8 file.

**Comment by KevCui** [comment] 2021-01-11 10:08
@Akianonymus Thanks for the hint, I will try.

**Comment by KevCui** [comment] 2021-01-11 21:41
Hi @DieVei, I want to understand your issue more clearly. I add the debug mode in the latest commit 4ea09e9. You could start script with the flag `-d` to enable the debug mode. Under the debug mode, all detailed logs will show up in the terminal, including `ffmpeg` logs. Hope this will help to debug your issue.

**Comment by DieVei** [comment] 2021-01-12 19:32
ok so after using the debug mode, this is what i found out. Apparently the dl downloads an episode by taking source and downloading everything in small bits which is supposed to make files download faster just like how IDM works. But here, the dl is downloading everything into sooo manyyyyyy small parts that it takes more time to connect to the sources and downloading the files then rather a 2 or 3 parts which will make it faster. There are two files attached, one shows how the dl connects to the source(.mp4) and one is the increment in episode size(.gif), which is like in kilobytes or hardly megabytes. I am also linking a pastebin of the logs. I might be completely wrong as i am a noob in linux and stuff but this is what I think.
pastebin pswd - CvLaPFw11c

https://pastebin.com/rZGjpgdv
https://user-images.githubusercontent.com/77189436/104362930-725b9200-553a-11eb-9a01-5aa6c8a8e53a.gif
https://user-images.githubusercontent.com/77189436/104362658-18f36300-553a-11eb-9e2b-d7963b5a0b9d.mp4

**Comment by KevCui** [comment] 2021-01-12 22:03
Hi @DieVei, thanks for the logs.

You're right about how `ffmpeg` works in the script. Actually, the playlist is used for streaming mainly that's why it contains so many small parts.

From your log, I see you got an average speed `speed=1.98x` on your Raspberry Pi. Since it's a Raspberry Pi, which doesn't have very powerful hardware, this speed may be normal for it? Need do some (re)searches to find more info about it.

**Comment by DieVei** [comment] 2021-01-12 22:40
hmm that might be the issue i guess. But i have a RPi 4B+, it has 4gigs of ram and i host a NAS on it so maybe this is not a hardware issue as the specs are enough to run some resource intensive OS'. And i am running the recc. raspberry Pi OS on it so there shouldn't be any compatibility issues too. But you might be right and it is not powerful enough to actually pull faster from the servers. I should try using a cloud vm for linux to test this. If i could and i get higher speeds, i'll let you know asap.

**Comment by djchittoor** [comment] 2021-01-19 14:40
The issue is being addressed in https://github.com/KevCui/animepahe-dl/pull/16

**Comment by djchittoor** [comment] 2021-01-22 12:45
@KevCui ig its safe to close this now :D

**Comment by KevCui** [comment] 2021-01-22 19:30
Hi, @DieVei, as @djchittoor mentioned above, the parallel download feature is now implemented in #16. To enable this feature, run script with `-t <num>` in the end. Here the `<num>` is the number of threads running in parallel, try `-t 50`, `-t 100`... to see the speed increasing.

**Closed** 2021-01-22 19:30 UTC
Labels: enhancement, help wanted, question
