### ISSUE TITLE
Anime Slug Not Found

### ISSUE THREAD

**Issue by Zeroo097** [KevCui/animepahe-dl#39] opened 2021-10-05 16:28 UTC
It doesn't recognise the name of the anime i tried the name both in English and Japanese but it doesn't seem to work.When i try english it shows anime slug not found when i try in Japanese it just stucks there nothing pops up

![IMG_20211005_215645.jpg](https://user-images.githubusercontent.com/91909890/136065953-4358c8c5-7b47-4338-9d34-063a5b353242.jpg)

**Comment by KevCui** [comment] 2021-10-05 18:34
Hi @Zeroo097, the English title in your screenshot has a typo, it should be `attack`, not `attck`. In case you don't see any outputs, please run command with `-d`, it will print out all debug logs.

**Comment by Zeroo097** [comment] 2021-10-06 05:08
Still the same problem no outputs were shown even after i corrected the typo.I am attaching the debug log below.


![image](https://user-images.githubusercontent.com/91909890/136143241-6370e93e-c457-4236-8d7f-48840e45adb8.png)

![BB](https://user-images.githubusercontent.com/91909890/136143697-185a81fa-c0d8-4f83-af0e-492bc9573512.png)

**Comment by Zeroo097** [comment] 2021-10-06 08:29
I deleted **anime.list** file and it did not help.Idk why but when i write jujutsu in anime name it recognises it and starts to download but when i write any other name it doesn't work btw i used tokyo for tokyo revengers.And how do i enable writing permission? Thank You for Help.

**Comment by KevCui** [comment] 2021-10-06 08:36
@Zeroo097 thanks for the info. I think the permission is correct. It may be an issue of `fzf`. Please try this command `echo "a\nb" | fzf -1`, are you able to use fzf to select "a" or "b" in the list?

**Comment by Zeroo097** [comment] 2021-10-06 09:08
When i wrote this command and pressed enter it did not ask me to do anything it gave output itself.

**Comment by KevCui** [comment] 2021-10-06 09:22
@Zeroo097, what's the output you saw? You should be able to select "a" or "b" in `fzf`. If not, something is wrong with your `fzf` installation/configuration.

**Comment by KevCui** [comment] 2021-10-06 09:23
Sorry, my bad, the command I posted in previous comment is wrong, try this `echo -e "a\nb" | fzf -1`

**Comment by parhamlans619** [comment] 2021-12-08 04:05
![Screenshot (58)](https://user-images.githubusercontent.com/95732812/145146412-10b59952-32c3-453b-ac63-9c1e8f4bc585.png)

**Comment by KevCui** [comment] 2021-12-09 12:36
Hi @parhamlans619, @Zeroo097 already tried to change to `.ru` in another issue ticket https://github.com/KevCui/animepahe-dl/issues/40#issuecomment-936958432 Unfortunately, it doesn't work.

**Comment by parhamlans619** [comment] 2021-12-09 12:42
> Hi @parhamlans619, @Zeroo097 already tried to change to `.ru` in another issue ticket [#40 (comment)](https://github.com/KevCui/animepahe-dl/issues/40#issuecomment-936958432) Unfortunately, it doesn't work.

How can I fix my issue? 443 error

**Comment by KevCui** [comment] 2022-01-24 06:46
Hi @Zeroo097, it's been months I didn't hear you back. I assume everything works now? If not, feel free to open new issue. I'm closing this issue since no more actions to be done on my side.

Hi @parhamlans619, 443 error can caused by server. Please open new issue with logs if it's still happening to you, I will for sure take another look there. Thanks.

**Closed by KevCui** 2022-01-24 06:46 UTC
